version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  springboot-app:
    image: springboot-app:latest
    container_name: loan-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/LoanApp
    depends_on:
      - mongo
